Add more digits to the delta of openDX
MDAnalysis/GridDataFormats pull request #89
Opened 2021-09-10 19:36 UTC by xiki-tempula

Fix #88

2021-09-10 19:37 UTC, pep8speaks commented
Hello @xiki-tempula! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`gridData/OpenDX.py`](https://github.com/MDAnalysis/GridDataFormats/blob/50d55b13f8c21d42bb23a5f27d7f911c08551538/gridData/OpenDX.py):

> [Line 244:80](https://github.com/MDAnalysis/GridDataFormats/blob/50d55b13f8c21d42bb23a5f27d7f911c08551538/gridData/OpenDX.py#L244): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2021-09-14 23:19 UTC, IAlibay requested changes
If you update against master CI should now be green (hopefully?)

I'll let @orbeckst do the final review here (since I'm technically new to this repo).

I _think_ you need to add yourself to AUTHORS?

2021-09-14 23:19 UTC, IAlibay commented on gridData/OpenDX.py
> +                stream, ('delta ' +
Do we need an extra test to check that your use case is now covered?

2021-09-14 23:32 UTC, orbeckst requested changes
Thanks for the PR, @xiki-tempula ; please add
- CHANGELOG
- AUTHORS
- small test that checks that the guaranteed number of digits is saved (and read) — maybe just use your example
- add entry to docs for OpenDX stating how we are saving (for instance, for PyMOL we have an entry on precision)

2021-09-15 21:08 UTC, orbeckst approved these changes

2021-09-15 21:09 UTC, orbeckst commented
Thanks @xiki-tempula !

@IAlibay do the latest changes address your concerns?

2021-09-15 21:18 UTC, IAlibay approved these changes
lgtm, just the one thing about the docs authorship

2021-09-17 04:45 UTC, merged